services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      RABBITMQ_URL: amqp://rabbitmq:5672
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      RABBITMQ_URL: amqp://rabbitmq:5672
      OTEL_SERVICE_NAME: payment-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://rabbitmq:5672
      OTEL_SERVICE_NAME: inventory-service
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://jaeger:4318/v1/traces
    depends_on:
      rabbitmq:
        condition: service_healthy
      jaeger:
        condition: service_started
